name: dementia_mobile
<<<<<<< HEAD
description: "A Flutter Web dementia patient app"
=======
description: "A new Flutter project."
>>>>>>> 25bbeaea32f89c467b1258f821d604b4e48deaa6
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
=======

>>>>>>> 25bbeaea32f89c467b1258f821d604b4e48deaa6
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
