<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-08-16 03:43
=======
# Generated by Django 5.1.5 on 2025-08-08 18:20
>>>>>>> 25bbeaea32f89c467b1258f821d604b4e48deaa6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('recording_file', models.FileField(upload_to='recordings/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('transcript', models.TextField(blank=True, null=True)),
=======
                ('audio_file', models.FileField(upload_to='recordings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
>>>>>>> 25bbeaea32f89c467b1258f821d604b4e48deaa6
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='users.patient')),
            ],
        ),
    ]
