# Generated by Django 5.1.5 on 2025-08-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='generated_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
